#### TEST USUARIO BUSCAR TODOS ##
GET {{baseurlapi}}/usuario/findAll
Accept: application/json

#### TEST CONSULTAR USUARIO ##
GET {{baseurlapi}}/usuario/findByUsuario/fwe
Accept: application/json

#### TEST VIDEOJUEGO REGISTRAR VIDEOJUEGO ##
POST {{baseurlapi}}/usuario/createUsuario
Content-Type: application/json

{
  "nombre": "Samuel",
  "usuario": "Sam",
  "telefono": "675849328",
  "contraseña": "xd",
  "mensajes": null
}

#### TEST ELIMINAR USUARIO ##
DELETE {{baseurlapi}}/usuario/deleteUsuario/Samuel
Accept: application/json
